import type { SleepingSession } from './sleeping.js';

export interface ExecResult {
  code: number;
  stdout: string;
  stderr: string;
}

export type ExecFn = (
  cmd: string,
  args: string[],
  opts?: { cwd?: string },
) => Promise<ExecResult>;

export interface FinishDeps {
  exec: ExecFn;
  notify: (msg: string) => Promise<void>;
}

function humanise(slug: string): string {
  return slug.replace(/-/g, ' ');
}

function buildBody(session: SleepingSession): string {
  return [
    '## Summary',
    '',
    'Automated implementation via `kuroboto sleeping` (sleep mode).',
    '',
    '## Original prompt',
    '',
    '```',
    session.prompt,
    '```',
    '',
    '## Test plan',
    '',
    '- [ ] Review the diff against the original prompt',
    '- [ ] Run the test suite locally',
    '- [ ] Smoke-test the new behavior end-to-end',
    '',
    '_Generated by kuroboto sleep mode._',
  ].join('\n');
}

export async function finishSleep(session: SleepingSession, deps: FinishDeps): Promise<void> {
  // 1. Push branch from the worktree
  const push = await deps.exec('git', ['push', '-u', 'origin', session.branch], {
    cwd: session.worktreePath,
  });
  if (push.code !== 0) {
    await deps.notify(
      `❌ sleep finalize failed — push failed: ${push.stderr.trim() || 'unknown'}. ` +
        `worktree: ${session.worktreePath}`,
    );
    return;
  }

  // 2. Query the repo's default branch
  let baseBranch = 'main';
  const view = await deps.exec('gh', ['repo', 'view', '--json', 'defaultBranchRef', '--jq', '.defaultBranchRef.name'], {
    cwd: session.worktreePath,
  });
  if (view.code === 0) {
    const trimmed = view.stdout.trim();
    if (trimmed) baseBranch = trimmed;
  }

  // 3. Create PR via gh
  const title = humanise(session.slug);
  const body = buildBody(session);
  const create = await deps.exec(
    'gh',
    ['pr', 'create', '--base', baseBranch, '--head', session.branch, '--title', title, '--body', body],
    { cwd: session.worktreePath },
  );
  if (create.code !== 0) {
    await deps.notify(
      `❌ sleep finalize failed — pr create failed: ${create.stderr.trim() || 'unknown'}. ` +
        `worktree: ${session.worktreePath}`,
    );
    return;
  }

  const url = create.stdout.trim().split('\n').pop() ?? '';
  await deps.notify(
    `✅ sleep done — PR: ${url}\n\nTest plan in the PR body. Worktree: ${session.worktreePath}`,
  );
}
